name: Build LaTeX document

on: 
  push:
  pull_request:
    types:
      - closed
    branches:
      - master



jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document Introduction
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides_RU/Introduction/

      - name: Compile LaTeX document Stability
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides_RU/Stability/

      - name: Compile LaTeX document Control
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides_RU/Control/




      - name: Save Introduction artifact
        uses: actions/upload-artifact@v4
        with:
          name: Introduction.pdf
          path: Slides_RU/Introduction/main.pdf
          
      - name: Save Stability artifact
        uses: actions/upload-artifact@v4
        with:
          name: Stability.pdf
          path: Slides_RU/Stability/main.pdf
          
      - name: Save Control artifact
        uses: actions/upload-artifact@v4
        with:
          name: Control.pdf
          path: Slides_RU/Control/main.pdf



      - name: Update compiled PDFs in git repository
        if: github.event.pull_request.merged == true || github.event_name == 'push'
        run: |
          mv Slides_RU/Introduction/main.pdf Slides_RU/Introduction.pdf
          mv Slides_RU/Stability/main.pdf Slides_RU/Stability.pdf
          mv Slides_RU/Control/main.pdf Slides_RU/Control.pdf
          
          git config --global user.name 'CI PDF compiler'
          git config --global user.email '<>'
          git add Slides_RU/Introduction.pdf
          git add Slides_RU/Stability.pdf
          git add Slides_RU/Control.pdf


          git commit -m "Update compiled PDFs"
          git push
